name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-server:
    name: Docker (Server)
    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect Builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Build and Push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          target: server
          platforms: linux/amd64,linux/arm64
          tags: dnys1/unpub:latest
          push: ${{ github.event_name != 'pull_request' }}
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        if: ${{ github.event_name != 'pull_request' }}
  docker-launcher:
    name: Docker (Launcher)
    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect Builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Build and Push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          target: launcher
          platforms: linux/amd64,linux/arm64
          tags: dnys1/unpub-launcher:latest
          push: ${{ github.event_name != 'pull_request' }}
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        if: ${{ github.event_name != 'pull_request' }}